//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetectorInspector {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DetectorInspector.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another user has modified the {0}. Please review the {0} to ensure that you still wish to delete it and then retry..
        /// </summary>
        internal static string DataCurrencyException_Delete_Message {
            get {
                return ResourceManager.GetString("DataCurrencyException_Delete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another user has modified the {0}. Please review the {0} to ensure that you still wish to modify it and then retry..
        /// </summary>
        internal static string DataCurrencyException_Edit_Message {
            get {
                return ResourceManager.GetString("DataCurrencyException_Edit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is currently in use and cannot be deleted. Please edit the {0} and flag it as inactive..
        /// </summary>
        internal static string EntityInUseException_Delete_Message {
            get {
                return ResourceManager.GetString("EntityInUseException_Delete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} &quot;{1}&quot; is required for the DetectorInspector system to function and as such cannot be deleted..
        /// </summary>
        internal static string SystemEntity_Delete_Message {
            get {
                return ResourceManager.GetString("SystemEntity_Delete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} you are currently editing is required by the DetectorInspector system to function..
        /// </summary>
        internal static string SystemEntity_Edit_Message {
            get {
                return ResourceManager.GetString("SystemEntity_Edit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} you specified is not unique. Please choose a different {0} and then retry..
        /// </summary>
        internal static string Unique_Property_Violation_Message {
            get {
                return ResourceManager.GetString("Unique_Property_Violation_Message", resourceCulture);
            }
        }
    }
}
